version: 0.2

phases: 
    build:
        commands:
            - echo "Build phase"
            - |
              # Deployment Script
              # Create /tmp/deployment directory
              sudo mkdir -p /tmp/deployment

              # Clone the repository to /tmp/deployment
              sudo git clone https://github.com/kamisettysurendra/surendra20112001- /tmp/deployment

              # Change to the cloned repository directory
              cd /tmp/deployment/surendra20112001-

              # List files in the cloned repository for debugging purposes
              echo "Listing files in /tmp/deployment/surendra20112001-:"
              ls -la

              # Ensure the target directory exists
              sudo mkdir -p /var/www/html

              # Remove all existing files and directories in /var/www/html
              echo "Removing all files in /var/www/html:"
              sudo rm -rf /var/www/html/*

              # Copy the entire directory structure to the web server directory
              echo "Copying files to /var/www/html:"
              sudo cp -r * /var/www/html

              # Verify the copied files
              echo "Listing files in /var/www/html:"
              ls -la /var/www/html
              
              # Clean up the temporary directory
              sudo rm -rf /tmp/deployment

    post_build:
        commands:
            - echo "Post-build phase"

artifacts:
    files:
        - assets/**
        - css/**/*
        - fonts/**/*
        - images/**/*
        - js/**/*
        - scripts/**/*
        - index.html
        - appspec.yml  
    discard-paths: yes
