version: 0.2

phases: 
    build:
        commands:
            - echo "Build phase"
            - |
              # Deployment Script
              # Clone the GitHub repository, build, and deploy

              # Clone the repository to a temporary directory
              sudo git clone https://github.com/kamisettysurendra/surendra20112001- /tmp/deployment

              # Change to the deployment directory
              cd /tmp/deployment

              # List files in the cloned repository for debugging purposes
              echo "Listing files in /tmp/deployment:"
              ls -la

              # Ensure the target directory exists
              sudo mkdir -p /var/www/html

              # Copy the built files to the web server directory
              echo "Copying files to /var/www/html:"
              sudo cp -r . /var/www/html

              # Verify the copied files
              echo "Listing files in /var/www/html:"
              ls -la /var/www/html/
              
              # Clean up the temporary directory
              cd /tmp
              sudo rm -rf /tmp/deployment

    post_build:
        commands:
            - echo "Post-build phase"

artifacts:
    files:
        - assets/**
        - css/**/*
        - fonts/**/*
        - images/**/*
        - js/**/*
        - scripts/**/*
        - index.html
        - appspec.yml  
    discard-paths: yes
