version: 0.2
phases: 
    build:
        commands:
            - echo "Post build phase"
            - |
              # Deployment Script
              # Clone the GitHub repository, build, and deploy
 
              # Clone the repository to a temporary directory
              sudo git clone https://github.com/kamisettysurendra/surendra20112001- /tmp/deployment
 
              # List files in the temporary directory to verify the clone
              ls /tmp/deployment/
              
              # Copy all files, including hidden ones, to the web server directory
              sudo cp -r /tmp/deployment/. /var/www/html
              
 
    post_build:
        commands:
            - echo "Post-build phase"
artifacts:
    files:
        - scripts/install_dependencies
        - scripts/start_server
        - scripts/stop_server
        - index.html
        - appspec.yml  
    discard-paths: yes
